### ISSUE TITLE
增加CRC32图片重命名方案

### ISSUE THREAD

**Issue by Alex-NKG** [wayjam/picgo-plugin-s3#10]
考虑到MD5出来的文件名还是过长了，能否提供类似CRC32这样的重命名方案？这样生成文件名较短

**Comment by Alex-NKG** [comment]
刚看了下openssl 没有CRC32，或者生成指定长度字符串也可以

**Comment by usrtax** [comment]
https://github.com/wayjam/picgo-plugin-s3/pull/20/files
加了2个函数，提交了一个合并请求

**Comment by wayjam** [comment]
> https://github.com/wayjam/picgo-plugin-s3/pull/20/files 加了2个函数，提交了一个合并请求

Merged at `v1.2.3`
