### ISSUE TITLE
没有自定义域名，图片 URL 的自定义前缀应该如何设置？

### ISSUE THREAD

**Issue by plumcyt** [wayjam/picgo-plugin-s3#16]
没有自定义域名，使用B2时，请问自定义前缀应该如何设置？设置为 https://fxxx.backblazeb2.com/file/bucket-name 和 https://bucket-name.s3.us-west-004.backblazeb2.com 或者放空都上传失败。Error 是 invalid URL。

**Comment by wayjam** [comment]
`v1.2.0`引入的 BUG，麻烦升级到 `v1.2.1` 及以上重试一下。
