### ISSUE TITLE
ACL 权限是否可以改成启用和不启用

### ISSUE THREAD

**Issue by peytonyip** [wayjam/picgo-plugin-s3#17]
安装的插件是 1.2.1，目前权限配置为必填项，用的 cloudflare R2 还没支持这个，会提示：
![image](https://user-images.githubusercontent.com/28802445/200150313-d7f5fee7-31c6-4e8e-8c8d-dcaffab50490.png)

R2 目前支持的 API：https://developers.cloudflare.com/r2/data-access/s3-api/api/

鉴于 R2 或者 minio 等可以直接设定整个桶的权限，这里的 ACL 权限是否可以改成启用和不启用呢？

**Comment by wayjam** [comment]
`v1.2.2`修复了ACL必填的问题。然后ACL填写 `private`即可。

**Comment by peytonyip** [comment]
新版测试 OK 了，感谢！

**Comment by SnrtIevg** [comment]
ALC 的值要是有个说明就好了， 

这个是抄录的s3.d.ts的内容，做个记录
```js
export type ObjectCannedACL = "private"|"public-read"|"public-read-write"|"authenticated-read"|"aws-exec-read"|"bucket-owner-read"|"bucket-owner-full-control"|string;
```
