### ISSUE TITLE
现在上传会自动在根目录加一层目录名为"桶名"，能否更新一下返回的链接地址吗？

### ISSUE THREAD

**Issue by murazi** [wayjam/picgo-plugin-s3#25]
现在自动复制的链接里，缺少新的“桶名”，所以每次都要手动加一遍

希望作者可以修复这个问题，因为我是才用到这个插件，我一直以为自己配置的不对，检查了好久才发现- -

假设桶名为:123

现在的链接地址
`https://haha.abc.com/abbbbbbb.webp`

正确的地址:
`https://haha.abc.com/123/abbbbbbb.webp`

如果在配置路径里前面手动添加桶名
实际上它又会变为
`https://haha.abc.com/123/123/abbbbbbb.webp`

**Comment by wayjam** [comment]
是最新的 `v1.3.0` 吗？ `pathStyleAccess` 的开关是开还是关？完整配置贴一下

**Comment by murazi** [comment]
> 是最新的 `v1.3.0` 吗？ `pathStyleAccess` 的开关是开还是关？完整配置贴一下

抱歉，我忘了说，我使用的是cloudflare r2的s3服务

没错插件是1.3.0
我试过，pathStyleAccess的开关并无影响

我现在的解决办法是，在自定义链接的后缀上，再加一次桶名，这样可以解决问题
如果amazon的s3无此问题的话，建议在md里可以向r2服务的用户单独声明一下这样解决的方法

r2就是会在自定义域名后，自动再加一层目录“bulkName”

**Comment by wayjam** [comment]
不同 S3 Provider 的配置方法：https://github.com/wayjam/picgo-plugin-s3/issues/28

**Comment by wangyunsi** [comment]
sO,这个问题并没有解决，总是在自定义域名后自动加一次桶名，而且，每上传一张照片，自动加一次

**Comment by wayjam** [comment]
> 

有参照这个配置方法吗 https://github.com/wayjam/picgo-plugin-s3/issues/28
