### ISSUE TITLE
CloudFlare R2 无法正常访问

### ISSUE THREAD

**Issue by CZT0** [wayjam/picgo-plugin-s3#26]
配置好S3后，日志显示上传成功，但是实际未上传
<img width="483" alt="image" src="https://user-images.githubusercontent.com/49915976/233796818-8ee76178-699e-45c9-9fe6-eb1a301b6b7c.png">

**Comment by wayjam** [comment]
R2 Web页面上看下是否到了别的目录

**Comment by CZT0** [comment]
确实上传到markdown目录下了，这个是可以更改的吗，我想传到根目录下
