### ISSUE TITLE
升级到1.30版本后上传返回的链接不正确

### ISSUE THREAD

**Issue by guan5444** [wayjam/picgo-plugin-s3#27]
使用S3接口，调用Oracle云以及minio均出现如下问题

1.30以前版本返回的链接
https://minio.duob.top:58443/dubodata01/2023/04/e1b4f07eefcb8012fc1499e644220bd1.png
1.30版本返回的链接
https://minio.duob.top:58443/dubodata01/2023/04/d8a88c9995eba801c8f9a4236d7e8bc6.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=IryuMx1mVNnVAUfO%252F20230424%252Fauto%252Fs3%252Faws4_request&X-Amz-Date=20230424T154532Z&X-Amz-Expires=3600&X-Amz-Signature=1093c27d84a0910c5fb61f784e479d26293e8d2e342bc245dd605d61251876d4&X-Amz-SignedHeaders=host%253Bif-match&x-id=GetObject

多了后面的一串信息，删掉就可以正常访问。
?X-Amz-Algorithm=AWS4-HM....

**Comment by wayjam** [comment]
Released `v1.3.1`
