### ISSUE TITLE
网页上传可以,域名也反代弄好了, 但是插件一直无法上传

### ISSUE THREAD

**Issue by mayixb** [wayjam/picgo-plugin-s3#33]
不知道是哪里出问题了,自定义域名去掉也不可以
![image](https://github.com/wayjam/picgo-plugin-s3/assets/133849519/2a2cc57a-26bf-49bc-af21-175db8f31dce)
![image](https://github.com/wayjam/picgo-plugin-s3/assets/133849519/ae38d8dc-cbf1-4d6b-bd37-cbb36fc95ecf)

**Comment by wayjam** [comment]
B2 使用 S3 API上传不能直接使用 Master Key，需新建 Application Key 使用。进入 Account - Application Keys 新建一个 Application Key 来填入配置中使用。

**Comment by StrokMitream** [comment]
> 不知道是哪里出问题了,自定义域名去掉也不可以 ![image](https://private-user-images.githubusercontent.com/133849519/255312441-2a2cc57a-26bf-49bc-af21-175db8f31dce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NzkwMTMsIm5iZiI6MTcyOTc3ODcxMywicGF0aCI6Ii8xMzM4NDk1MTkvMjU1MzEyNDQxLTJhMmNjNTdhLTI2YmYtNDliYy1hZjIxLTE3NWRiOGYzMWRjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxNDA1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzIxYjU4MDkzZGEyZjBmMTk5ZWZmYzBlYTg2NWY4ZWM1MjVhNDdmZWI3NGI1NjVkZTVlYWJhMDExMjE3MWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.AMtpuLZk3e-c711Ilq6UDM2P7zmLzNiz0Npd4lULfzY) ![image](https://private-user-images.githubusercontent.com/133849519/255312444-ae38d8dc-cbf1-4d6b-bd37-cbb36fc95ecf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NzkwMTMsIm5iZiI6MTcyOTc3ODcxMywicGF0aCI6Ii8xMzM4NDk1MTkvMjU1MzEyNDQ0LWFlMzhkOGRjLWNiZjEtNGQ2Yi1iZDM3LWNiYjM2ZmM5NWVjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxNDA1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGYxOWQ3ZjcwMzRmNDdkMzVmYTMxOWNlMTlkYjllM2U3NGE5NWQ3M2VlOTU2M2ExOTBkMTVjMTVhMWExZTM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.B2gZa8rpUZezuWMMLi7x2OMiGElfBxypDxOu-8Ohkwk)

acl 那个“public read ”策略注意一下, 我这边测试的时候发现, 报错log 是这个 acl.
