### ISSUE TITLE
建议上传路径支持 payload 增加 Unix 时间戳，在uPic图床工具里对应的是{since_millisecond}，Obsidian 里模板命名也支持 X 表示自动用时间戳生成文件名，谢谢

### ISSUE THREAD

**Issue by xxhk-org** [wayjam/picgo-plugin-s3#34]
建议上传路径支持 payload 增加 Unix 时间戳，在uPic图床工具里对应的是{since_millisecond}，Obsidian 里模板命名也支持 X 表示自动用时间戳生成文件名，谢谢

> Unix时间戳是一种时间表示方式，从1970年1月1日（UTC/GMT的午夜）开始所经过的秒数，不考虑闰秒。它通常用于计算机系统中记录和表示时间。

**Comment by wayjam** [comment]
Release `v1.3.4`，新增 `{timestamp}` / `{timestampMS}`。
