### ISSUE TITLE
返回的链接不可用

### ISSUE THREAD

**Issue by Idealisten** [wayjam/picgo-plugin-s3#37]
返回的图片链接打开后显示XML错误，去CF上查看上传文件的公共存储桶链接是可以正常打开图片的，但是那个S3链接打开后会报同样的XML错误

**Comment by wayjam** [comment]
返回的 S3 链接是未签名链接。具体 S3 权限说明在这https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html

**Comment by Idealisten** [comment]
啊，但是我是上传到CloudFlare的R2的呀

WayJam So ***@***.***> 于2023年9月4日周一 00:30写道：

**Comment by Kuingsmile** [comment]
> 返回的图片链接打开后显示XML错误，去CF上查看上传文件的公共存储桶链接是可以正常打开图片的，但是那个S3链接打开后会报同样的XML错误

把自定义域名设置成R2的公开域名地址或者绑定的自己的域名了么
