### ISSUE TITLE
GUI 显示问题

### ISSUE THREAD

**Issue by wRyjer** [wayjam/picgo-plugin-s3#4]
![image](https://user-images.githubusercontent.com/62415784/110095145-8e134400-7dd7-11eb-9666-037317e8d0e6.png)

如上图所示，GUI界面无法显示全部选项，下面的**确认**按钮无法使用。
也没有滚动条。不知是GUI的问题还是插件的问题

**Comment by wayjam** [comment]
好的，我检查一下。

**Comment by loveshizuka** [comment]
是的，我也遇到这个问题。不过暂时可以通过按 Tab 键填写被遮挡的表单和保存操作。

**Comment by wayjam** [comment]
GUI版没有支持滚动，看样子在GUI版本已修复，<https://github.com/Molunerfinn/PicGo/pull/635/>，可以期待新版发布。
