### ISSUE TITLE
请老大看看上传文件只能是2G的问题

### ISSUE THREAD

**Issue by fscarmen** [wayjam/picgo-plugin-s3#48]
我在 picGO 那反馈问题，他建议我过来找你，简单的说就是经过 awscli 和 node 的依赖    aws-sdk/client-s3 和 aws-sdk/lib-storage 都能上传 10G大文件，但通过本插件只能是2G以内的，详细的在下面有，有劳了。
https://github.com/Molunerfinn/PicGo/issues/1296

**Comment by wayjam** [comment]
### 结论：

是的，只能上传2G。

### 原因：

现行 PicGo 架构下，会调用 node 同步方法 `readFile` 来读取整个文件
> 源码 <https://github.com/PicGo/PicGo-Core/blob/dev/src/utils/common.ts#L57>,
代码抛出的堆栈是：

```
[ERR_FS_FILE_TOO_LARGE]: File size (2254438400) is greater than 2 GiB error
```

> 源码：<https://sourcegraph.com/github.com/nodejs/node@b5056be8544345ae4dd53601400240479f99b9a1/-/blob/lib/fs.js?L325>
> <https://sourcegraph.com/github.com/nodejs/node@b5056be8544345ae4dd53601400240479f99b9a1/-/blob/lib/internal/fs/utils.js?L133>

这一步骤还没到S3插件阶段。

### 是否能解决

理论上是可以解决的。但如同 PicGo 作者所说，需插件自行接管获取读取文件的流程。我认为，如果这样做那等同于一个独立的工具，可以不依赖 PicGo 了，那实际上现有的工具是已经存在的，所以 PicGo S3 插件应该不会做这样的事。另外，确实在 [Molunerfinn/PicGo/issues/1296#issuecomment-2509742566](https://github.com/Molunerfinn/PicGo/issues/1296#issuecomment-2509742566) 所说的似乎超过 2Gib 大小的图片的场景是比较小的。

**Comment by fscarmen** [comment]
> 所说的似乎超过 2Gib 大小的图片的场景是比较小的

我现在使用并不是单纯视作图库，而是多个 R2，B2 桶，连接 Github , Gitlab 等组成一个分布式的储存集群。后续估计有的文件超过2G，所以就想看看有没有办法处理。

这样看来的确是 PicGO 本体处理较妥当。不过这个需求较个性化，也可以理解 Molunerfinn 没有动力处理，也只能如此了。
