### ISSUE TITLE
删除时 似乎 S3 存储桶内的资源没有被一起删除. 不知道是不是我配置的问题?

### ISSUE THREAD

**Issue by orangejx** [wayjam/picgo-plugin-s3#6]
删除时 似乎 S3 存储桶内的资源没有被一起删除. 不知道是不是我配置的问题?
![ScreenShot 2021-08-30.jpg](http://static-cdn.ora.pub/img/2021/08/30/35607101fbbc5d00d80c689d57f8b5bbb25d67732ae465a6f19499bb0583712c.png)

**Comment by wayjam** [comment]
PicGo没有提供删除通知到插件的接口。所以插件是感知不到删除事件的，目前只有上传功能，不太适合做管理云存储。
